version: '3.0'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --username user --password admin --authenticationDatabase admin --eval \"db.adminCommand('ping')\""]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "5001:8000"
    volumes:
      - .:/code
    environment:
        MONGO_URI: "mongodb://user:admin@mongodb:27017/main?authSource=admin"
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_PORT: 5672
        RABBITMQ_USER: user
        RABBITMQ_PASSWORD: admin
        RABBITMQ_QUEUE: player_tasks
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    volumes:
      - .:/code
    environment:
      MONGO_URI: "mongodb://user:admin@mongodb:27017/?authSource=admin"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: admin
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    command: python app/worker.py

volumes:
  mongo_data: